# Generated by Django 5.1.3 on 2024-11-26 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_alter_user_table'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrvdata',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='sleeprecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='sleeprecord',
            name='hrv_data',
        ),
        migrations.AlterField(
            model_name='hrvdata',
            name='sleep_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrv_readings', to='accounts.sleeprecord'),
        ),
        migrations.AlterField(
            model_name='hrvdata',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='quality_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hrvdata',
            index=models.Index(fields=['sleep_record', 'timestamp'], name='accounts_hr_sleep_r_68e995_idx'),
        ),
        migrations.AddIndex(
            model_name='sleeprecord',
            index=models.Index(fields=['user', '-created_at'], name='accounts_sl_user_id_fb13cf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='auth_user_usernam_f2740e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
    ]
